version: '3.8'

services:
  hive-frontend-service:
    container_name: hive-frontend
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
       - ../src:/app/src
       - /node_modules
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
